# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Hexify
version:      0.02
version_from: lib/Data/Hexify.pm
installdirs:  site
requires:
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
